// Code generated by scripts/generate_data.go. DO NOT EDIT.
// Source: https://github.com/intoli/user-agents
// Generated: 2026-09-12T07:32:55Z

package ua

// Chrome versions extracted from real usage data (sorted by popularity)
var chromeVersions = []string{
	"116.0.0.0",
	"131.0.0.0",
	"133.0.6943.141",
	"139.0.0.0",
	"144.0.0.0",
	"145.0.0.0",
	"146.0.0.0",
	"147.0.0.0",
	"148.0.0.0",
	"148.0.7778.96",
	"149.0.0.0",
	"150.0.0.0",
	"151.0.0.0",
	"152.0.0.0",
	"153.0.0.0",
	"154.0.0.0",
	"42.0.2157.1158",
	"49.0.2527.1661",
	"52.0.3222.1095",
	"54.0.1356.1718",
}

// Firefox versions extracted from real usage data
var firefoxVersions = []string{
	"115.0",
	"140.0",
	"146.0",
	"150.0",
	"152.0",
	"153.0",
	"154.0",
	"155.0",
}

// Safari versions extracted from real usage data
var safariVersions = []string{
	"15.4",
	"16.6.1",
	"17.0",
	"17.1",
	"17.14",
	"17.3.1",
	"17.4.1",
	"17.6",
	"18.3",
	"18.6",
	"26.2",
	"26.3",
	"26.4",
	"26.5",
	"26.5.2",
	"26.6",
	"26.6.1",
	"26.6.2",
	"27.0",
	"8.0.2",
}

// Edge versions extracted from real usage data
var edgeVersions = []string{
	"146.0.0.0",
	"150.0.0.0",
	"151.0.0.0",
	"152.0.0.0",
	"153.0.0.0",
}

// Windows NT versions (sorted by popularity)
var windowsVersions = []string{
	"10.0",
	"6.3",
}

// macOS versions (underscore format: 14_2_1)
var macVersions = []string{
	"10_10_1",
	"10_15_7",
	"14_3_1",
	"14_6",
	"11_0",
	"11_6",
	"12_0",
	"12_6",
	"13_0",
	"13_6",
	"14_0",
	"14_4",
	"15_0",
}

// Linux desktop platforms extracted from real usage data
var linuxDesktops = []string{
	"X11; Linux x86_64",
	"X11; Linux x86_64; Chromium",
	"X11; Linux i686",
	"X11; Linux aarch64",
	"X11; Ubuntu; Linux x86_64",
	"X11; Fedora; Linux x86_64",
	"X11; Debian; Linux x86_64",
	"X11; Arch Linux; Linux x86_64",
	"X11; CentOS; Linux x86_64",
}

// iOS versions (underscore format: 17_4_1)
var iosVersions = []string{
	"11_0",
	"14_4",
	"16_7_16",
	"17_4_1",
	"17_6_1",
	"18_2",
	"18_3",
	"18_3_2",
	"18_4",
	"18_5",
	"18_6",
	"18_6_2",
	"18_7",
	"18_7_8",
	"26_3_1",
	"26_5_0",
	"26_5_2",
	"26_6_0",
	"26_6_1",
	"26_6_2",
}

// Android versions
var androidVersions = []string{
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"16",
	"5",
	"6",
	"8",
}

// Android devices extracted from real usage data (model, build ID)
var androidDevices = []struct {
	model string
	build string
}{
	{"RMX3690", "SP1A.210812.016"},
	{"SM-S931W", "BP4A.251205.006"},
	{"SM-S936U", "BP4A.251205.006"},
	{"SM-S947U", "BP4A.251205.006"},
	{"Pixel 6", "TQ3A.230901.001"},
	{"Pixel 7", "TQ3A.230901.001"},
	{"Pixel 7 Pro", "TQ3A.230901.001"},
	{"Pixel 8", "UQ1A.231205.015"},
	{"Pixel 8 Pro", "UQ1A.231205.015"},
	{"SM-S901B", "TP1A.220624.014"},
	{"SM-S908B", "TP1A.220624.014"},
	{"SM-S911B", "TP1A.220624.014"},
	{"SM-S918B", "TP1A.220624.014"},
	{"SM-S921B", "UP1A.231005.007"},
	{"SM-S928B", "UP1A.231005.007"},
	{"SM-A536B", "TP1A.220624.014"},
	{"SM-A546B", "UP1A.231005.007"},
	{"SM-G998B", "TP1A.220624.014"},
	{"ONEPLUS A6013", "QKQ1.190716.003"},
	{"IN2025", "RKQ1.211119.001"},
	{"CPH2451", "TP1A.220905.001"},
	{"M2101K6G", "TKQ1.221114.001"},
	{"2201116SG", "TKQ1.221114.001"},
	{"23049PCD8G", "UKQ1.231003.002"},
	{"RMX3363", "TP1A.220905.001"},
	{"V2111", "TP1A.220624.014"},
	{"LE2125", "RKQ1.211119.001"},
}

// WebKit version (used in Safari)
const webkitVersion = "605.1.15"

// AppleWebKit version for Chrome/Edge
const appleWebKitChrome = "537.36"
