// Code generated by scripts/generate_data.go. DO NOT EDIT.
// Source: https://github.com/intoli/user-agents
// Generated: 2026-01-18T14:12:30Z

package ua

// Chrome versions extracted from real usage data (sorted by popularity)
var chromeVersions = []string{
	"109.0.0.0",
	"114.0.0.0",
	"116.0.0.0",
	"122.0.0.0",
	"125.0.0.0",
	"128.0.0.0",
	"129.0.0.0",
	"130.0.0.0",
	"131.0.0.0",
	"132.0.0.0",
	"137.0.0.0",
	"138.0.0.0",
	"139.0.0.0",
	"140.0.0.0",
	"141.0.0.0",
	"142.0.0.0",
	"143.0.0.0",
	"43.0.9500.1535",
	"56.0.8271.1481",
	"99.0.4844.51",
}

// Firefox versions extracted from real usage data
var firefoxVersions = []string{
	"115.0",
	"133.0",
	"140.0",
	"143.0",
	"144.0",
	"145.0",
	"146.0",
	"147.0",
	"148.0",
	"78.0",
}

// Safari versions extracted from real usage data
var safariVersions = []string{
	"15.5",
	"15.6.1",
	"16.5.1",
	"16.6",
	"16.6.1",
	"17.0",
	"17.14",
	"17.6",
	"18.1",
	"18.3",
	"18.4",
	"18.5",
	"18.6",
	"18.7",
	"18.7.2",
	"18.7.3",
	"26.1",
	"26.2",
	"60.5",
	"8.0.2",
}

// Edge versions extracted from real usage data
var edgeVersions = []string{
	"123.0.0.0",
	"125.0.0.0",
	"138.0.0.0",
	"139.0.0.0",
	"140.0.0.0",
	"141.0.0.0",
	"142.0.0.0",
	"143.0.0.0",
	"144.0.0.0",
}

// Windows NT versions (sorted by popularity)
var windowsVersions = []string{
	"10.0",
	"6.1",
	"6.2",
}

// macOS versions (underscore format: 14_2_1)
var macVersions = []string{
	"10_10_1",
	"10_12_0",
	"10_13_0",
	"10_14_0",
	"10_15_6",
	"10_15_7",
	"11_0",
	"11_6",
	"12_0",
	"12_6",
	"13_0",
	"13_6",
	"14_0",
	"14_4",
	"15_0",
}

// Linux desktop platforms extracted from real usage data
var linuxDesktops = []string{
	"X11; Linux aarch64",
	"X11; Linux x86_64",
	"X11; Ubuntu; Linux x86_64",
	"X11; Linux i686",
	"X11; Fedora; Linux x86_64",
	"X11; Debian; Linux x86_64",
	"X11; Arch Linux; Linux x86_64",
	"X11; CentOS; Linux x86_64",
}

// iOS versions (underscore format: 17_4_1)
var iosVersions = []string{
	"11_0",
	"16_7_12",
	"17_4_1",
	"17_5_1",
	"17_6_1",
	"18_1_1",
	"18_3_1",
	"18_3_2",
	"18_5",
	"18_5_0",
	"18_6",
	"18_6_1",
	"18_6_2",
	"18_7",
	"18_7_1",
	"18_7_2",
	"26_1",
	"26_1_0",
	"26_2_0",
	"26_3_0",
}

// Android versions
var androidVersions = []string{
	"10",
	"11",
	"12",
	"13",
	"15",
	"16",
	"5",
	"6",
	"8",
	"9",
}

// Android devices extracted from real usage data (model, build ID)
var androidDevices = []struct {
	model string
	build string
}{
	{"SM-A205W", "RP1A.200720.012"},
	{"SM-S921W", "AP3A.240905.015.A2"},
	{"SM-S937W", "BP2A.250605.031.A3"},
	{"UTBook_15", "AP3A.241105.008"},
	{"Pixel 6", "TQ3A.230901.001"},
	{"Pixel 7", "TQ3A.230901.001"},
	{"Pixel 7 Pro", "TQ3A.230901.001"},
	{"Pixel 8", "UQ1A.231205.015"},
	{"Pixel 8 Pro", "UQ1A.231205.015"},
	{"SM-S901B", "TP1A.220624.014"},
	{"SM-S908B", "TP1A.220624.014"},
	{"SM-S911B", "TP1A.220624.014"},
	{"SM-S918B", "TP1A.220624.014"},
	{"SM-S921B", "UP1A.231005.007"},
	{"SM-S928B", "UP1A.231005.007"},
	{"SM-A536B", "TP1A.220624.014"},
	{"SM-A546B", "UP1A.231005.007"},
	{"SM-G998B", "TP1A.220624.014"},
	{"ONEPLUS A6013", "QKQ1.190716.003"},
	{"IN2025", "RKQ1.211119.001"},
	{"CPH2451", "TP1A.220905.001"},
	{"M2101K6G", "TKQ1.221114.001"},
	{"2201116SG", "TKQ1.221114.001"},
	{"23049PCD8G", "UKQ1.231003.002"},
	{"RMX3363", "TP1A.220905.001"},
	{"V2111", "TP1A.220624.014"},
	{"LE2125", "RKQ1.211119.001"},
}

// WebKit version (used in Safari)
const webkitVersion = "605.1.15"

// AppleWebKit version for Chrome/Edge
const appleWebKitChrome = "537.36"
