// Code generated by scripts/generate_data.go. DO NOT EDIT.
// Source: https://github.com/intoli/user-agents
// Generated: 2026-09-26T08:12:58Z

package ua

// Chrome versions extracted from real usage data (sorted by popularity)
var chromeVersions = []string{
	"121.0.0.0",
	"125.0.0.0",
	"129.0.0.0",
	"131.0.0.0",
	"138.0.0.0",
	"139.0.0.0",
	"140.0.0.0",
	"143.0.0.0",
	"144.0.0.0",
	"145.0.0.0",
	"146.0.0.0",
	"147.0.0.0",
	"148.0.0.0",
	"149.0.0.0",
	"150.0.0.0",
	"151.0.0.0",
	"152.0.0.0",
	"153.0.0.0",
	"154.0.0.0",
	"54.0.6694.1672",
}

// Firefox versions extracted from real usage data
var firefoxVersions = []string{
	"127.0",
	"140.0",
	"152.0",
	"153.0",
	"154.0",
	"155.0",
	"156.0",
	"157.0",
	"158.0",
}

// Safari versions extracted from real usage data
var safariVersions = []string{
	"15.6.1",
	"16.3",
	"16.6",
	"16.6.2",
	"17.4.1",
	"17.6",
	"18.5",
	"18.6",
	"18.7.5",
	"18.7.6",
	"26.2",
	"26.3",
	"26.3.1",
	"26.4",
	"26.5",
	"26.5.2",
	"26.6",
	"26.6.1",
	"26.6.2",
	"27.0",
}

// Edge versions extracted from real usage data
var edgeVersions = []string{
	"124.0.0.0",
	"150.0.0.0",
	"151.0.0.0",
	"152.0.0.0",
	"153.0.0.0",
	"154.0.0.0",
}

// Windows NT versions (sorted by popularity)
var windowsVersions = []string{
	"10.0",
	"6.1",
}

// macOS versions (underscore format: 14_2_1)
var macVersions = []string{
	"10_15_6",
	"10_15_7",
	"10_15_8",
	"14_6",
	"26_5_2",
	"11_0",
	"11_6",
	"12_0",
	"12_6",
	"13_0",
	"13_6",
	"14_0",
	"14_4",
	"15_0",
}

// Linux desktop platforms extracted from real usage data
var linuxDesktops = []string{
	"X11; Linux x86_64",
	"X11; Linux i686",
	"X11; Linux aarch64",
	"X11; Ubuntu; Linux x86_64",
	"X11; Fedora; Linux x86_64",
	"X11; Debian; Linux x86_64",
	"X11; Arch Linux; Linux x86_64",
	"X11; CentOS; Linux x86_64",
}

// iOS versions (underscore format: 17_4_1)
var iosVersions = []string{
	"11_0",
	"17_4_1",
	"17_5_1",
	"17_6_1",
	"18_2",
	"18_3",
	"18_4",
	"18_5",
	"18_6",
	"18_6_2",
	"18_7",
	"18_7_8",
	"26_3_1",
	"26_5_0",
	"26_5_2",
	"26_6_0",
	"26_6_1",
	"26_6_2",
	"26_7_0",
	"27_0_0",
}

// Android versions
var androidVersions = []string{
	"10",
	"11",
	"14",
	"15",
	"16",
	"17",
	"5",
	"6",
	"8",
	"9",
}

// Android devices extracted from real usage data (model, build ID)
var androidDevices = []struct {
	model string
	build string
}{
	{"KFTUWI", "RS8338.3339N"},
	{"SM-S938U", "BP4A.251205.006"},
	{"Pixel 6", "TQ3A.230901.001"},
	{"Pixel 7", "TQ3A.230901.001"},
	{"Pixel 7 Pro", "TQ3A.230901.001"},
	{"Pixel 8", "UQ1A.231205.015"},
	{"Pixel 8 Pro", "UQ1A.231205.015"},
	{"SM-S901B", "TP1A.220624.014"},
	{"SM-S908B", "TP1A.220624.014"},
	{"SM-S911B", "TP1A.220624.014"},
	{"SM-S918B", "TP1A.220624.014"},
	{"SM-S921B", "UP1A.231005.007"},
	{"SM-S928B", "UP1A.231005.007"},
	{"SM-A536B", "TP1A.220624.014"},
	{"SM-A546B", "UP1A.231005.007"},
	{"SM-G998B", "TP1A.220624.014"},
	{"ONEPLUS A6013", "QKQ1.190716.003"},
	{"IN2025", "RKQ1.211119.001"},
	{"CPH2451", "TP1A.220905.001"},
	{"M2101K6G", "TKQ1.221114.001"},
	{"2201116SG", "TKQ1.221114.001"},
	{"23049PCD8G", "UKQ1.231003.002"},
	{"RMX3363", "TP1A.220905.001"},
	{"V2111", "TP1A.220624.014"},
	{"LE2125", "RKQ1.211119.001"},
}

// WebKit version (used in Safari)
const webkitVersion = "605.1.15"

// AppleWebKit version for Chrome/Edge
const appleWebKitChrome = "537.36"
